### PR TITLE
Localization replacement

### LINKED ISSUE #252: Swap add liquidity url should contain BNB instead of ETH
**Bug Description**
Swap add liquidity url should contain BNB instead of ETH

**Steps to Reproduce**

1. Click Trade on the left Menu
2. Click Liquidity
3. Click Add Liquidity
4. Check default URL. It is https://exchange.pancakeswap.finance/#/add/ETH

**Expected Behavior**
It should be It is https://exchange.pancakeswap.finance/#/add/BNB

### PR DESCRIPTION
**Pull request by Chef-Chungus**
Fix #252

### CODE REVIEW

File: src/components/PageHeader/SlippageToleranceSetting.tsx [hunk 1]
```diff
@@ -46,46 +46,46 @@ const predefinedValues = [
...
       } else {
-        setError('Enter a valid slippage percentage')
+        setError(TranslateString(999, 'Enter a valid slippage percentage'))
       }
     } catch {
-      setError('Enter a valid slippage percentage')
+      setError(TranslateString(999, 'Enter a valid slippage percentage'))
     }
-  }, [value, setError, setUserslippageTolerance])
+  }, [value, setError, setUserslippageTolerance, TranslateString])
```
[the remark this answers is not in the document]
Comment (hachiojidev) [reply src/components/PageHeader/SlippageToleranceSetting.tsx:73]: @Chef-Chungus I think @RabbitDoge is right that it will cause this to run each re-render. He also noted that the translation context is not even used and we can probably move it out of being a hook and I agree.

As a temporary workaround I memoized the function and made the commit on this branch. This should allow it to be called inside an effect without causing issues.

File: src/pages/RemoveLiquidity/index.tsx [hunk 2]
```diff
@@ -540,15 +542,15 @@ export default function RemoveLiquidity({
...
-                              Receive WBNB
+                              {TranslateString(999, 'Receive WBNB')}
                             </StyledInternalLink>
                           ) : oneCurrencyIsWETH ? (
                             <StyledInternalLink
                               to={`/remove/${
-                                currencyA && currencyEquals(currencyA, WETH[chainId]) ? 'ETH' : currencyIdA
-                              }/${currencyB && currencyEquals(currencyB, WETH[chainId]) ? 'ETH' : currencyIdB}`}
+                                currencyA && currencyEquals(currencyA, WETH[chainId]) ? 'BNB' : currencyIdA
+                              }/${currencyB && currencyEquals(currencyB, WETH[chainId]) ? 'BNB' : currencyIdB}`}
```
Comment (Chef-Chungus) [inline src/pages/RemoveLiquidity/index.tsx:551]: Need confirmation that it's OK to change these @RabbitDoge

Comment (RabbitDoge) [reply src/pages/RemoveLiquidity/index.tsx:563]: It will at least breaks some links on the FE

**Review by RabbitDoge — APPROVED** [review]

File: src/pages/RemoveLiquidity/index.tsx (hunk 2 above)
Comment (RabbitDoge) [reply src/pages/RemoveLiquidity/index.tsx:563]: Solved here https://github.com/pancakeswap/pancake-frontend/pull/634
